### ISSUE TITLE
Headers and footers are not appearing

### ISSUE THREAD

**Issue by koenhandekyn** [palapala-app/palapala_pdf#1]
There's an issue with headers and footers not appearing. It might be related to camel casing. Ferrum does some strange processing of the snake case params to convert them automatically to the camel cased parameters that chrome is expecting. But it's unclear if that is the issue.

Further, in Grover based experiments, i also found that chrome itself is pretty picky on the styles required on the html snippet. 

There's a test script (manual) under test/headers_and_footers.rb.

**Comment by codenighter** [comment]
@koenhandekyn This works:

```
Palapala::PDF.new("<p>Hello world</>").save("test.pdf", displayHeaderFooter: true, footerTemplate: '<div style="text-align: center; font-size: 12pt;"><span>Generated with Palapala PDF</div>')
```

pass the options to `save`, and in the `footerTemplate` you HAVE to specify the `font-size`. Otherwise is set to `0`, because... reasons.

**Comment by koenhandekyn** [comment]
yeah thanks. if you passed the params on the save it worked as these params where passed as is through to the library. there was a typo in the params from the constructor. 

there's a new version that is another order faster, it basically does the web socket communication directly. feel free to test it on e.g. claims. the API stayed the same and the initializer bug is fixed.
